# -*- coding: utf-8 -*-
"""calculator-gas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NAv2WWtvftmT15sLiMV91rVqb6im9JjQ

# **Calculadora de Combustível**
"""

qtd = float(input('Digite a quantidade de combustível a ser comprada (Litros): '))
tipo = input('Digite o combustível que deseja: "E" -> Etanol ou "D" -> Diesel): ').upper()
etanol = float(1.70)
diesel = float(2.00)

if (qtd <= 15) and (tipo == 'E'):
  desconto = (etanol * qtd * 0.02)
  pagamento = (etanol * qtd)
  pagamento_desc = (etanol * qtd) - desconto
  print(f'Quantidade solicitada: {qtd} | Valor do Etanol: R$ 1,70 | Total Desconto: {desconto} | Valor total: R${pagamento} | Valor total COM DESCONTO: R${pagamento_desc}')
elif (qtd > 15) and (tipo == 'E'):
  desconto = (etanol * qtd * 0.04)
  pagamento = (etanol * qtd)
  pagamento_desc = (etanol * qtd) - desconto
  print(f'Quantidade solicitada: {qtd} | Valor do Etanol: R$ 1,70 | Total Desconto: {desconto} | Valor total: R${pagamento} | Valor total COM DESCONTO: R${pagamento_desc}')
elif (qtd <= 15) and (tipo == 'D'):
  desconto = (diesel * qtd * 0.03)
  pagamento = (diesel * qtd)
  pagamento_desc = (diesel * qtd) - desconto
  print(f'Quantidade solicitada: {qtd} | Valor do Diesel: R$ 2,00 | Total Desconto: {desconto} | Valor total: R${pagamento} | Valor total COM DESCONTO: R${pagamento_desc}')
elif (qtd > 15) and (tipo == 'D'):
  desconto = (diesel * qtd * 0.05)
  pagamento = (diesel * qtd)
  pagamento_desc = (diesel * qtd) - desconto
  print(f'Quantidade solicitada: {qtd} | Valor do Diesel: R$ 2,00 | Total Desconto: {desconto} | Valor total: R${pagamento} | Valor total COM DESCONTO: R${pagamento_desc}')
else:
  print('Desculpe, não foi possível calcular seu desconto e pagamento, insira um valor válido.')
