# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MdhJrISm9rMaEiqEl_7ECUR7OugadCyT

# ***Calculadora + Informações***

Este projeto permite que você realize operações artiméticas e obtenha informações sobre o resultado.
"""

n1 = float(input(f'Digite um número: '))
n2 = float(input(f'Digite um número: '))
question = input('Qual operação você deseja realizar? (+ , - , *, //, %)')

#Define Operação
if question == '+':
  result = n1 + n2
elif question == '-':
  result = n1 - n2
elif question == '*':
  result = n1 * n2
elif question == '//':
  result = n1 // n2
elif question == '%':
  result = n1 % n2
else:
  print('Operação inválida')

#Informações da operação:
print(f'- A operação realizada entre os dois números obteve o resultado: {result}')

#Mensagem para melhorar a usabilidade
print('- Aguarde, você receberá uma lista de informações sobre o resultado da sua operação: ...')

#Verifica se é par ou ímpar
if result % 2 == 0:
  print('- Seu número é par;')
else:
  print('- Seu número é impar;')

#Verifica se é positivo ou negativo
if result > 0:
  print('- Seu número é positivo;')
else:
  print('- Seu número é negativo;')

#Verifica se é inteiro ou decimal
if result % 1 == 0:
  print('- Seu numero é inteiro.')
else:
  print('- Seu número é decimal.')