# -*- coding: utf-8 -*-
"""sell-analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqlsQsTNT7hoM6cKmGWByW-p2eutBMD4

# **Análise de Vendas**
Em uma empresa de venda de imóveis você precisa criar um código que analise os dados de vendas anuais para ajudar a diretoria na tomada de decisão. É preciso coletar os dados de quantidade de venda durante os anos de 2022 e 2023 e fazer um cálculo de variação percentual. A partir do valor da variação, deve ser enviada às seguintes sugestões:
- Para variação acima de 20%: bonificação para o time de vendas.
- Para variação entre 2% e 20%: pequena bonificação para time de vendas.
- Para variação entre 2% e -10%: planejamento de políticas de incentivo às vendas.
- Para bonificações abaixo de -10%: corte de gastos.
"""

venda22 = float(input('Digite a quantidade de vendas no ano de 2022: '))
venda23 = float(input('Digite a quantidade de vendas no ano de 2023: '))

variacao = ((venda23 - venda22) / venda22) * 100

if variacao > 20:
  print('Time de Vendas será bonificado!')
elif variacao >= 2 and variacao <= 20:
  print('Time de Vendas terá uma pequena bonificação.')
elif variacao >= -10 and variacao < 2:
  print('Planejamento de políticas de incentivo às vendas, não há bonificação!')
elif variacao < -10:
  print('Será necessário aplicar a politica de corte de gastos.')
else:
  print('Erro: Por favor, verifique o valor inserido.')