# -*- coding: utf-8 -*-
"""exec

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neL6sDK9SMLl_Cn3Vzf0nO6Wbl4rgYoR

### Questão 1

Imprima a frase `Escola de Dados da Alura!`
"""

print('escola de dados da alura!')

"""### Questão 2
Imprima na tela seu nome e seu sobrenome seguindo a estrutura abaixo:
```
Nome: [seu nome]
Sobrenome: [seu sobrenome]
```

"""

print('nome: rafaela')
print('sobrenome: concimo')

"""### Questão 3
Imprima o seu primeiro nome letra a letra. Por exemplo, nome é Mirla, então eu obtenho a seguinte saída:
```
M
I
R
L
A
```

"""

print('r')
print('a')
print('f')
print('a')
print('e')
print('l')
print('a')

"""### Questão 4
Imprima o dia do seu nascimento em formato `dia mês ano`. Os valores de dia e ano não podem estar entre aspas. O formato deve estar como no exemplo, supondo uma data de aniversário dia 28 de fevereiro de 2003:
```
28 fevereiro 2003
```
"""

print(24,'outubro',2001)

"""### Questão 5
Imprima em um único print o atual ano que você está fazendo esse curso, o valor do ano deve ser um dado numérico. A saída do print deve ser a seguinte:
```
Ano atual: [ano]
```

"""

#isso é um comentário
print('2025')

"""## Aula 2 - Manipulando dados no Python

### Coleta e amostragem de dados
"""

print(input('Digite seu nome: '))

"""#### Questão 1
Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.
"""

nome = input("Digite seu nome: ")
print(f'Olá, {nome}!')

"""#### Questão 2
Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”.
"""

nome = input("Digite seu nome: ")
idade = input("Digite sua idade: ")
print(f'Olá, {nome}, você tem {idade} anos.')

"""#### Questão 3
Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”.
"""

nome=input('Digite seu nome: ')
idade=input('Digite sua idade: ')
altura=input('Digite sua altura em metros: ')
print(f'Olá, {nome}, você tem {idade} anos e mede {altura} metros!')

"""### Calculadora com operadores

#### Questão 1

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.
"""

num_1 = int(input("Digite o primeiro valor: "))
num_2 = int(input("Digite o segundo valor: "))
sum = num_1 + num_2
print(f'A soma entre {num_1} + {num_2} resulta em: {sum}')

"""#### Questão 2
Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.
"""

num1 = int(input("Insira o primeiro valor: "))
num2 = int(input('Insira o segundo valor: '))
num3 = int(input('Insira o terceiro valor: '))
sum_values= num1 + num2 + num3
print(f'A soma entre os três valores digitados é: {sum_values}')

"""#### Questão 3
Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.
"""

num_1 = int(input('Digite um valor: '))
num_2 = int(input('Digite o segundo valor: '))
sub = num_1 - num_2
print(f'A subtração entre os dois números citados é: {sub}')

"""#### Questão 4

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.

"""

num_1 = int(input('Digite um valor: '))
num_2 = int(input('Digite o segundo valor: '))
mult = num_1 * num_2
print(f'O valor da multiplicação entre os dois valores digitados é: {mult}')

"""#### Questão 5

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.

"""

num1 = int(input('Digite um numerador: '))
num2 = int(input('Digite um denomidador que seja maior que o nº 0: '))
div = num1 / num2
print(f'A divisão entre o numerador e o denominador citados é: {div}')

"""#### Questão 6

Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.

"""

num1 = int(input('Digite um operador: '))
num2 = int(input('Digite sua potência: '))
expo = num1**num2
print(f'A exponenciação entre os dois valores citados resulta em: {expo}')

"""#### Questão 7
Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`.
"""

num1 = int(input('Defina um numerador: '))
num2 = int(input('Defina um denominador: '))
div_int = num1//num2
print(f'A divisão inteira entre dois numeros se resultou em: {div_int}')

"""
#### Questão 8

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser `0`."""

numerador = int(input('Digite um numerador: '))
denominador = int(input('Digite um denominador que seja diferente de 0: '))
result = numerador%denominador
print(f'O resto da divisão entre os nº resultou em: {result}')

"""#### Questão 9

Crie um código que solicita 3 notas de um estudante e imprima a média das notas.
"""

nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))
nota3 = float(input('Digite a terceira nota:'))
media_notas = (nota1 + nota2 + nota3) / 3
print(f'A média das notas citadas acima é: {media_notas}')

"""#### Questão 10

Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.
"""

n1 = 5*1
n2 = 12*2
n3 = 20*3
n4 = 15*4
soma_peso = 10
media_ponderada = (n1+n2+n3+n4) / soma_peso
print(f'A média ponderada entre os valores é: {media_ponderada}')

"""### Editando textos

#### Questão 1

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.
"""

frase = 'Olá!'
print(frase)

"""#### Questão 2
Crie um código que solicite uma frase e depois imprima a frase na tela.
"""

frase = input('Digite uma frase: ')
print(frase)

"""#### Questão 3

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.
"""

frase = input('Digite uma frase: ')
print(frase.upper())

"""#### Questão 4

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.
"""

frase = input('Digite uma frase: ')
print(frase.lower())

"""#### Questão 5

Crie uma variável chamada “`frase`” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.
"""

frase = 'Oiii'
print(frase.strip())

"""#### Questão 6

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.
"""

frase = input('Digite uma frase: ')
print(frase.strip())

"""#### Questão 7


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.
"""

frase = input('Digite sua frase: ')
print(frase.lower().strip())

"""#### Questão 8

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`e`” trocadas pela letra “`f`”.
"""

frase = input('Digite uma frase: ')
print(frase.replace('e','f'))

"""#### Questão 9


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “`a`” trocadas pela caractere  “`@`”.
"""

frase = input('Digite uma frase')
print(frase.replace('a', chr(64))) #aqui é a mesma coisa que o de cima, porém, com a diferença que estamos utilizando o código do caractere baseado na tabela unicode

"""#### Questão 10


Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “`s`” trocadas pelo caractere  “`$`”.
"""

frase = input('Digite aqui sua frase: ')
print(frase.replace('s',chr(36)))

"""## Aula 3 - Estruturas condicionais

### Aquecendo na programação

#### Questão 1
Escreva um programa que peça à pessoa usuária para fornecer dois números e exibir o número maior.
"""

num1 = float(input('Digite um número:'))
num2 = float(input('Digite outro numero:'))

if num1 > num2:
  print(f'O maior número é: {num1}')
else:
  print(f'O maior número é: {num2}')

"""#### Questão 2
Escreva um programa que solicite o percentual de crescimento de produção de uma empresa e informe se houve um crescimento (porcentagem positiva) ou decrescimento (porcentagem negativa).
"""

#Versão com IF cascata
 p1 = float(input('Digite o ultimo percentual: '))
 p2 = float(input('Digite o novo percentual: '))

 if p1 < p2:
  result = p2 - p1
  print(f'Houve um crescimento de {result}% em comparação ao último percentual.')
 if p1 == p2:
  print(f'A porcentagem está equiparada a ultima.')
 if p1 > p2:
  result2 = p1 - p2
  print(f'(Atenção!) Houve um decrescimento de {result2}% em comparação ao último percentual.')

#Outra versão do exercício acima, porém utilizando o elif e não IF cascata
p1 = float(input('Digite o ultimo percentual: '))
p2 = float(input('Digite o novo percentual: '))

if p1 < p2:
 result = p2 - p1
 print(f'Houve um crescimento de {result}% em comparação ao último percentual.')
elif p1 > p2:
 result2 = p1 - p2
 print(f'(Atenção!) Houve um decrescimento de {result2}% em comparação ao último percentual.')
else:
  print(f'A porcentagem está equiparada a ultima.')

"""
#### Questão 3
Escreva um programa que determine se uma letra fornecida pela pessoa usuária é uma vogal ou consoante."""

letter = (input('Digite uma letra: '))
vogal = 'a,e,i,o,u'

if letter in vogal:
  print('Esta letra é uma vogal.')
else:
  print('Esta letra é uma consoante.')

#formato diferente que também roda
letter = (input('Digite uma letra: '))
vogal = ['a','e','i','o','u']

if letter in vogal:
  print('Esta letra é uma vogal.')
else:
  print('Esta letra é uma consoante.')

"""#### Questão 4
Escreva um programa que leia valores médios de preços de um modelo de carro por 3 anos consecutivos e exiba o valor mais alto e mais baixo entre esses três anos.
"""

value1 = float(input('Digite o valor do primeiro ano do carro: '))
value2 = float(input('Digite o valor do segundo ano do carro: '))
value3 = float(input('Digite o valor do terceiro ano do carro: '))

#Decobrindo o maior número:
maior = value1
if value2 > maior:
  maior = value2
if value3 > maior:
  maior = value3

#Descobrindo o menor número:
menor = value1
if value2 < menor:
  menor = value2
if value3 < menor:
  menor = value3

print(f'O maior valor é: R${maior} e o menor valor é: R${menor}')

"""#### Questão 5
Escreva um programa que pergunte sobre o preço de três produtos e indique qual é o produto mais barato para comprar.
"""

preco_prod1 = float(input('Digite o preço do produto 1: '))
preco_prod2 = float(input('Digite o preço do produto 2: '))
preco_prod3 = float(input('Digite o preço do produto 3: '))

#Descobrindo o menor preço:
menor = preco_prod1
if preco_prod2 < menor:
  menor = preco_prod2
if preco_prod3 < menor:
  menor = preco_prod3

print(f'O menor preço é: R${menor}')

"""#### Questão 6
Escreva um programa que leia três números e os exiba em ordem decrescente.
"""

n1 = int(input('Digite N1: '))
n2 = int(input('Digite N2: '))
n3 = int(input('Digite N3: '))

#Descobrindo o maior valor
maior = n1
if n2 > maior:
  maior = n2
  if n3 > maior:
    maior = n3
print(f'Maior Nº: {maior}')

#Descobrindo o menor valor
menor = n1
if n2 < menor:
  menor = n2
if n3 < menor:
  menor = n3
print(f'Menor Nº: {menor}')

#Descobrindo o Intermedio

if n1 != maior and n1 != menor:
  intermedio = n1
if n2 != maior and n2 != menor:
  intermedio = n2
else:
  intermedio = n3
print(f'Nº intermedio: {intermedio}')

print(f'{maior},{intermedio},{menor}')

"""222#### Questão 7
Escreva um programa que pergunte em qual turno a pessoa usuária estuda ("manhã", "tarde" ou "noite") e exiba a mensagem "Bom Dia!", "Boa Tarde!", "Boa Noite!", ou "Valor Inválido!", conforme o caso.
"""

nome = input('Olá, favor informar seu nome:')
turno = input(f'Olá, {nome}, por favor, informe seu turno para estudos (manhã, tarde ou noite):')

if turno == 'manhã':
  print(f'Bom dia, {nome}!')
elif turno == 'tarde':
  print(f'Boa tarde, {nome}')
elif turno == 'noite':
  print(f'Boa noite, {nome}')
else:
  print(f'Desculpe, {nome}, você inseriu um valor inválido.')

"""exec 1 Usando só if, if, if, else, verifique:

se a idade é maior ou igual a 18 → "Adulto"

se a idade é maior ou igual a 13 → "Adolescente"

se a idade é maior ou igual a 0 → "Criança"

caso contrário → "Idade inválida"


exec 2 use apenas if, elif, elif, else
"""

idade = int(input('Digite sua idade: '))

if idade >= 18:
  print(f'Você possui {idade} anos, portanto você é um(a) adulto(a)!')
if idade >= 13:
  print(f'Você possui {idade} anos, portanto você é um(a) adolescente!')
if idade >= 0:
  print(f'Você possui {idade} anos, portanto você é um(a) criança!')
else:
  print('Idade Inválida!')

idade = int(input('Digite sua idade: '))

if idade >= 18:
  print(f'Você possui {idade} anos, portanto você é um(a) adulto(a)!')
elif idade >= 13:
  print(f'Você possui {idade} anos, portanto você é um(a) adolescente!')
elif idade >= 0:
  print(f'Você possui {idade} anos, portanto você é um(a) criança!')
else:
  print('Idade Inválido!')

"""#### Questão 8
Escreva um programa que peça um número inteiro à pessoa usuária e determine se ele é par ou ímpar. Dica: Você pode utilizar o operador módulo `%`.
"""

num = int(input('Digite um numero inteiro: '))

if num % 2 == 0:
  print(f'o número: {num} é par')
else:
  print(f'o número: {num} é ímpar')

"""#### Questão 9
Escreva um programa que peça um número à pessoa usuária e informe se ele é inteiro ou decimal.
"""

num = float(input('Digite um número: '))

if num % 1 == 0:
  print(f'O número: {num} é inteiro!')
else:
  print(f'O número: {num} é decimal!')